spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Winter365/ms-config-server.git
          username: test@sina.com
          password: test

data:
  test: hiclient
