spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Winter365/ms-config-server.git
          username: liwentang365@sina.com
          password: Li7488901

data:
  test: hi
